// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc.proto

package com.daydreamer.raft.api.grpc;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * payload
   * </pre>
   *
   * <code>string data = 1;</code>
   * @return The data.
   */
  String getData();
  /**
   * <pre>
   * payload
   * </pre>
   *
   * <code>string data = 1;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();

  /**
   * <pre>
   * conn id
   * </pre>
   *
   * <code>string id = 2;</code>
   * @return The id.
   */
  String getId();
  /**
   * <pre>
   * conn id
   * </pre>
   *
   * <code>string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * request or response type
   * </pre>
   *
   * <code>string type = 3;</code>
   * @return The type.
   */
  String getType();
  /**
   * <pre>
   * request or response type
   * </pre>
   *
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
